
on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  generatesbom:
    runs-on: ubuntu-latest
    name: generate_sbom
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install
      - name: Generate SBoM
        run: mvn dependency:tree -DoutputFile=sbom.txt  # 生成SBoM，保存到sbom.txt文件
      - name: Upload SBoM
        uses: actions/upload-artifact@v2
        with:
            ame: sbom
            path: sbom.txt  # 上傳SBoM文件

    build_and_push:
      name: Build & Push to DockerHub
      needs: slscan
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v4 
      - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
      - name: Login to DockerHub
        uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build with Maven
        run: mvn clean install
      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: breeze6167/devsecopsdiy:1.0 
    
